import { ICONS } from './svg-icon.constant';
import { SvgIconTypes } from './svg-icon.enum';

interface IconsMapping {
    [name: number]: Object;
}

export const ICONS_MAPPING: IconsMapping = {
    [SvgIconTypes.ADD]: ICONS.add,
    [SvgIconTypes.ADD_CIRCLE]: ICONS.addCircle,
    [SvgIconTypes.ADOBE]: ICONS.adobe,
    [SvgIconTypes.ALIGN_CENTRE]: ICONS.alignCentre,
    [SvgIconTypes.ALIGN_LEFT]: ICONS.alignLeft,
    [SvgIconTypes.ALIGN_RIGHT]: ICONS.alignRight,
    [SvgIconTypes.ANALYSIS]: ICONS.analysis,
    [SvgIconTypes.ARROW_RIGHT]: ICONS.arrowRight,
    [SvgIconTypes.BG_COLOUR]: ICONS.bgColour,
    [SvgIconTypes.BIN]: ICONS.bin,
    [SvgIconTypes.BOLD]: ICONS.bold,
    [SvgIconTypes.BURGER_MENU]: ICONS.burgerMenu,
    [SvgIconTypes.SHOW_MORE]: ICONS.showMore,
    [SvgIconTypes.CHART]: ICONS.chart,
    [SvgIconTypes.CHECKLIST]: ICONS.checklist,
    [SvgIconTypes.CHEVRON_DOWN]: ICONS.chevronDown,
    [SvgIconTypes.CHEVRON_LEFT]: ICONS.chevronLeft,
    [SvgIconTypes.CHEVRON_RIGHT]: ICONS.chevronRight,
    [SvgIconTypes.CLIP]: ICONS.clip,
    [SvgIconTypes.CLIPBOARD]: ICONS.clipboard,
    [SvgIconTypes.CLOSE]: ICONS.close,
    [SvgIconTypes.COLLAPSE]: ICONS.collapse,
    [SvgIconTypes.COLOUR]: ICONS.colour,
    [SvgIconTypes.COMMENTS]: ICONS.comments,
    [SvgIconTypes.COMMENTS_OUTLINE]: ICONS.commentsOutline,
    [SvgIconTypes.DATA_MAPPED]: ICONS.dataMapped,
    [SvgIconTypes.DATA_MAPPING]: ICONS.dataMapping,
    [SvgIconTypes.DATA_UNMAPPED]: ICONS.dataUnmapped,
    [SvgIconTypes.DOWN]: ICONS.down,
    [SvgIconTypes.DOWNLOAD]: ICONS.download,
    [SvgIconTypes.EDITOR]: ICONS.editor,
    [SvgIconTypes.ERROR]: ICONS.error,
    [SvgIconTypes.EXPAND]: ICONS.expand,
    [SvgIconTypes.FILE_ADD]: ICONS.fileAdd,
    [SvgIconTypes.FOLDER]: ICONS.folder,
    [SvgIconTypes.FULLSCREEN]: ICONS.fullscreen,
    [SvgIconTypes.GRID]: ICONS.grid,
    [SvgIconTypes.HISTORY]: ICONS.history,
    [SvgIconTypes.HOME]: ICONS.home,
    [SvgIconTypes.IMAGE]: ICONS.image,
    [SvgIconTypes.INDENT]: ICONS.indent,
    [SvgIconTypes.INFO]: ICONS.info,
    [SvgIconTypes.ITALIC]: ICONS.italic,
    [SvgIconTypes.KNOWLEDGE]: ICONS.knowledge,
    [SvgIconTypes.LINK]: ICONS.link,
    [SvgIconTypes.LOADING_SPINNER]: ICONS.loadingSpinner,
    [SvgIconTypes.LOCATION]: ICONS.location,
    [SvgIconTypes.MARKER]: ICONS.marker,
    [SvgIconTypes.MINUS]: ICONS.minus,
    [SvgIconTypes.MY_PROJECTS]: ICONS.myProjects,
    [SvgIconTypes.NO_DATA]: ICONS.noData,
    [SvgIconTypes.ORDERED_LIST]: ICONS.orderedList,
    [SvgIconTypes.OUTDENT]: ICONS.outdent,
    [SvgIconTypes.PEN]: ICONS.pen,
    [SvgIconTypes.PLUS]: ICONS.plus,
    [SvgIconTypes.POWERPOINT]: ICONS.powerpoint,
    [SvgIconTypes.PREVIEW]: ICONS.preview,
    [SvgIconTypes.PROJECT_SCOPE]: ICONS.projectScope,
    [SvgIconTypes.PROJECT_STRUCTURE]: ICONS.projectStructure,
    [SvgIconTypes.PROJECTS]: ICONS.projects,
    [SvgIconTypes.REMOVE_FORMATTING]: ICONS.removeFormatting,
    [SvgIconTypes.REPORT]: ICONS.report,
    [SvgIconTypes.REPORT_EMPTY]: ICONS.reportEmpty,
    [SvgIconTypes.SMART_WORKSPACE]: ICONS.smartWorkspace,
    [SvgIconTypes.RESIZE]: ICONS.resize,
    [SvgIconTypes.SAVE]: ICONS.save,
    [SvgIconTypes.SCOPE_ITEMS]: ICONS.scopeItems,
    [SvgIconTypes.SEARCH]: ICONS.search,
    [SvgIconTypes.SHARE]: ICONS.share,
    [SvgIconTypes.STAFF]: ICONS.staff,
    [SvgIconTypes.STRIKE]: ICONS.strike,
    [SvgIconTypes.SUBMIT]: ICONS.submit,
    [SvgIconTypes.SUBSCRIPT]: ICONS.subscript,
    [SvgIconTypes.SUCCESS]: ICONS.success,
    [SvgIconTypes.SUPERSCRIPT]: ICONS.superscript,
    [SvgIconTypes.TEAM]: ICONS.team,
    [SvgIconTypes.TEXT_TABLE]: ICONS.textTable,
    [SvgIconTypes.TICK]: ICONS.tick,
    [SvgIconTypes.TICK_CALENDAR]: ICONS.tickCalendar,
    [SvgIconTypes.UNDERLINE]: ICONS.underline,
    [SvgIconTypes.UNORDERED_LIST]: ICONS.unorderedList,
    [SvgIconTypes.UP]: ICONS.up,
    [SvgIconTypes.UPLOAD]: ICONS.upload,
    [SvgIconTypes.UPLOAD_IMAGE]: ICONS.uploadImage,
    [SvgIconTypes.UPLOAD_FILE]: ICONS.uploadFile,
    [SvgIconTypes.USER]: ICONS.user,
    [SvgIconTypes.SCALE]: ICONS.scale,
    [SvgIconTypes.DATA_EXPLORER]: ICONS.dataExplorer
};
